export const ACCESS_REQUESTS_PAGINATION = {
  ITEMS_PER_PAGE: 8,
};

export const MOCK_ACCESS_REQUESTS = [
  {
    id: 1,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 2,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 3,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 4,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 5,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 6,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 7,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 8,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 9,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 10,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
  {
    id: 11,
    requester: "Sankalp Jha",
    permission: "Financial Reports Access",
    duration: "1 month",
    status: "Pending" as const,
    requestedDate: "01-11-2025",
  },
];
