export const AUDIT_LOGS_PAGINATION = {
  ITEMS_PER_PAGE: 8,
};

export const MOCK_AUDIT_LOGS = [
  {
    id: 1,
    timestamp: "2025-11-02 10:30 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Pending",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 2,
    timestamp: "2025-11-02 10:25 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Pending",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 3,
    timestamp: "2025-11-02 10:20 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Approved",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 4,
    timestamp: "2025-11-02 10:15 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Pending",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 5,
    timestamp: "2025-11-02 10:10 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Approved",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 6,
    timestamp: "2025-11-02 10:05 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Pending",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 7,
    timestamp: "2025-11-02 10:00 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Pending",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 8,
    timestamp: "2025-11-02 09:55 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Pending",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 10,
    timestamp: "2025-11-02 09:50 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Approved",
    beforeAfterDiff: "View Changes",
  },
  {
    id: 11,
    timestamp: "2025-11-02 09:50 AM",
    actor: "Sankalp Jha",
    action: "1 month",
    target: "Pending",
    beforeAfterDiff: "View Changes",
  },
];
