export const USERS_PAGINATION = {
  ITEMS_PER_PAGE: 9,
};

export const MOCK_USERS = [
  {
    id: 1,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 2,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 3,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Inactive" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 4,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 5,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 6,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 7,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Inactive" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 8,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Inactive" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 9,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 10,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
  {
    id: 11,
    name: "Sankalp Jha",
    email: "user123@gmail.com",
    department: "Finance",
    role: "Finance manager",
    status: "Active" as const,
    lastLogin: "22-10-2025",
  },
];
