export const expenseData = [
  {
    date: "15/11/25",
    category: "Staffing",
    amount: "₹18,500",
    vendor: "Zenith HR",
    status: "Pending",
  },
  {
    date: "14/11/25",
    category: "Transport",
    amount: "₹6,200",
    vendor: "Fleetgo Logistics",
    status: "Approve",
  },
  {
    date: "12/11/25",
    category: "Equipment",
    amount: "₹40,000",
    vendor: "ProTech Machines",
    status: "Pending",
  },
  {
    date: "09/11/25",
    category: "Supplies",
    amount: "₹11,250",
    vendor: "Global Supply Co",
    status: "Approve",
  },
  {
    date: "07/11/25",
    category: "Transport",
    amount: "₹7,900",
    vendor: "Rapid Movers",
    status: "Approve",
  },
  {
    date: "06/11/25",
    category: "Staffing",
    amount: "₹21,000",
    vendor: "Talentize Solutions",
    status: "Pending",
  },
  {
    date: "04/11/25",
    category: "Supplies",
    amount: "₹13,700",
    vendor: "FreshMart",
    status: "Approve",
  },
  {
    date: "01/11/25",
    category: "Equipment",
    amount: "₹35,000",
    vendor: "Machina Works",
    status: "Pending",
  },
];
